### ISSUE TITLE
没法用啊

### ISSUE THREAD

**Issue by pixel32** [astroboylrx/DoubanBookCovers#1]
输入ID之后程序都崩溃了。用户id输入框尝试了以下格式“50947734”；“user_id_50947734”；“user_id=50947734”。

**Comment by astroboylrx** [comment]
@pixel32  豆瓣更改了访问数据的权限，所以之前的不能用了。现在暂时加入了一个网上的apikey，重新下载试试吧。

**Comment by astroboylrx** [comment]
那个user id只用填数字就可以了，不需要字母
